# Generated by Django 2.1.7 on 2019-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxapp',
            name='id',
        ),
        migrations.AlterField(
            model_name='wxapp',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
